=== oleksapanchuk/tax-app/src/main/resources/user.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="root">
        <xsd:complexType>
            <xsd:sequence>

                <xsd:element name="user" minOccurs="0" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>

                            <xsd:element name="id_user">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:int">
                                        <xsd:minInclusive value="1"/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>

                            <xsd:element name="first_name">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:pattern value="[A-ZА-Я][a-zа-я]*"/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>

                            <xsd:element name="last_name">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:pattern value="[a-zA-Zа-яіА-Я]+([ '-][a-zA-Zіа-яА-Я]+)*"/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>

                            <xsd:element name="sex">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:enumeration value="male"/>
                                        <xsd:enumeration value="female"/>
                                        <xsd:enumeration value="other"/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>

                            <xsd:element name="email">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string"/>
                                </xsd:simpleType>
                            </xsd:element>

                            <xsd:element name="date_of_birth">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:date">
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>


                            <xsd:element name="taxes">
                                <xsd:complexType>
                                    <xsd:sequence>

                                        <xsd:element name="tax" minOccurs="0" maxOccurs="unbounded">
                                            <xsd:complexType>

                                                <xsd:sequence>

                                                    <xsd:element name="id_payment">
                                                        <xsd:simpleType>
                                                            <xsd:restriction base="xsd:int"/>
                                                        </xsd:simpleType>
                                                    </xsd:element>

                                                    <xsd:element name="tax_id">
                                                        <xsd:simpleType>
                                                            <xsd:restriction base="xsd:int">
                                                                <xsd:enumeration value="1"/>
                                                                <xsd:enumeration value="2"/>
                                                                <xsd:enumeration value="3"/>
                                                                <xsd:enumeration value="4"/>
                                                                <xsd:enumeration value="5"/>
                                                                <xsd:enumeration value="6"/>
                                                                <xsd:enumeration value="7"/>
                                                            </xsd:restriction>
                                                        </xsd:simpleType>
                                                    </xsd:element>

                                                    <xsd:element name="value">
                                                        <xsd:simpleType>
                                                            <xsd:restriction base="xsd:double"/>
                                                        </xsd:simpleType>
                                                    </xsd:element>

                                                    <xsd:element name="amount_of_tax">
                                                        <xsd:simpleType>
                                                            <xsd:restriction base="xsd:double"/>
                                                        </xsd:simpleType>
                                                    </xsd:element>

                                                    <xsd:element name="payment_date">
                                                        <xsd:simpleType>
                                                            <xsd:restriction base="xsd:date"/>
                                                        </xsd:simpleType>
                                                    </xsd:element>

                                                </xsd:sequence>
                                            </xsd:complexType>
                                        </xsd:element>

                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>

                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>

            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== oleksapanchuk/tax-app/xml/user.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="user.xsd">
    <user>
        <id_user>1</id_user>
        <first_name>Mark</first_name>
        <last_name>Smoliak</last_name>
        <sex>male</sex>
        <email>smoliak23@gmail.com</email>
        <date_of_birth>2003-12-18</date_of_birth>
        <taxes>
            <tax>
                <id_payment>321</id_payment>
                <tax_id>1</tax_id>
                <value>3423.312</value>
                <amount_of_tax>1677.4228799999999</amount_of_tax>
                <payment_date>2002-04-05</payment_date>
            </tax>
        </taxes>
    </user>
    <user>
        <id_user>612456</id_user>
        <first_name>Gran</first_name>
        <last_name>Barnum</last_name>
        <sex>male</sex>
        <email>abrabak@gmail.com</email>
        <date_of_birth>2004-01-12</date_of_birth>
        <taxes/>
    </user>
</root>

=== oleksapanchuk/tax-app/src/main/resources/test_user.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="user.xsd">
    <user>
        <id_user>1</id_user>
        <first_name>Mark</first_name>
        <last_name>Smoliak</last_name>
        <sex>male</sex>
        <email>smoliak23@gmail.com</email>
        <date_of_birth>2003-12-18</date_of_birth>
        <taxes/>
    </user>
</root>
